title: 'webdevops.io'
languageCode: 'en-us'
theme: loveit

params:
  title: webdevops.io
  description: Cloud solutions

  defaultTheme: dark

  header:
    title:
      name:
      logo: /static/logo.png
  home:
    profile:
      subtitle:
        cloud solutions
      disclaimer: |
        <br><br><a href="https://discord.gg/BpBZtXAgJz">join discord</a><br><br>
        <img class="webdevops-logo" src="/static/logo.png">

  footer:
    since: 2023
    license: webdevops.io
  app:
    title: webdevops.io

  social:
    GitHub: https://github.com/webdevops/
  share:
    enable: false

  page:
    library:
        css:
          webdevops: /static/webdevops.css

menu:
  main:
  - identifier: projects
    name: projects
    pre: <i class="fa-solid fa-cubes"></i>
    url: /projects/
    weight: 20
  - identifier: members
    name: members
    pre: <i class="fa-solid fa-people-group"></i>
    url: /members/
    weight: 40
  - identifier: coc
    name: code of conduct
    pre: <i class="fa-regular fa-handshake"></i>
    url: /code-of-conduct/
    weight: 60
#   - identifier: github
#     name: github
#     pre: <i class="fa-brands fa-github"></i>
#     url: https://github.com/webdevops/
#     weight: 10000
#     params:
#       rel: external
  - name: Imprint
    pre: <i class="fa-solid fa-circle-info"></i>
    url: /imprint
    weight: 10001
